### ISSUE TITLE
Feature request: Setup and teardown functions

### ISSUE THREAD

**Issue by hmvp** [rust-fuzz/cargo-fuzz#101]
Maybe I missed something in the docs But I'd like to request the following feature:

Add a function that will be called once before the fuzzing starts to set up stuff needed for fuzzing. Maybe with a method to pass that data as an argument to the fuzz function. 

Two reasons:
- Expensive setup means the fuzzer runs slower. I would have used lazy_static but it does not play nice with the sanitizer
- Some setup is to cumbersome to do every test. I am currently fuzzing a program that accepts CAN packets and I need to setup a virtual can network beforehand. This would also need a teardown function.

**Comment by Manishearth** [comment]
There's not much we can do aside from using lazy_static here. Turn off the sanitizer option that errors on that, I guess?
