### ISSUE TITLE
Feature request: allow fuzz function to signal error in harness

### ISSUE THREAD

**Issue by hmvp** [rust-fuzz/cargo-fuzz#103]
I have a fuzz function that translates 12 bytes to a CAN frame. 4 for the header and up to 8 for the payload. If the fuzzer gets passed less than 4 or more then 12 it will reject and return immediately. This still results in a case in the corpus. 

It would be nice to be able to return a result that signals that the input is not valid at all and that it will not end up in the corpus. Maybe even something like:

```
enum FuzzerResult {
    InputToShort,
    InputToLong,
    ErrorInHarness,
}
```

**Comment by Manishearth** [comment]
libfuzzer doesn't have support for this.

However, given the way libfuzzer works, this doesn't matter. Let it put the string in the corpus, it will notice further strings light up the same code paths and ignore them.
