### ISSUE TITLE
Support for fuzzing timeout

### ISSUE THREAD

**Issue by lilianmoraru** [rust-fuzz/cargo-fuzz#116]
Could you please add a timeout flag/feature to `cargo-fuzz`(exiting with `0` if no problems were found)?
First time I saw this in `zstd`'s `test` target.
It runs the fuzzer for 5 minutes on compressions, than 2 minutes on zbufftest and 2 minutes on zstreamtest(9 minutes of fuzzing).
This would be useful in CI(you cannot run continuously).

**Comment by lilianmoraru** [comment]
I just observed the `-runs` in `run.sh`.
I still think the timeout is useful because you can precisely control how much time the fuzzing will run - CIs usually have an exact amount of time they wait for output, if nothing appears, it fails.

**Comment by nagisa** [comment]
You can already do this by appending `-- -max_total_time=seconds`. Use `-- -help=1` to see all the underlying options.

**Comment by Manishearth** [comment]
`cargo fuzz run foo -- -timeout some_timeout`

﻿Cargo fuzz accepts all libfuzzer arguments: http://llvm.org/docs/LibFuzzer.html#id16

(We could be better at documenting this, thoughts, @frewsxcv ?)

**Comment by Manishearth** [comment]
Yeah, we should document `-- -help=1` somewhere

**Comment by nagisa** [comment]
-timeout is wrong. This is the time until a single test run is considered to be a failure.

**Comment by Manishearth** [comment]
Added some commandline docs in https://github.com/rust-fuzz/cargo-fuzz/pull/117
