### ISSUE TITLE
Add --sanitizer=none

### ISSUE THREAD

**Issue by mateon1** [rust-fuzz/cargo-fuzz#129]
Currently it is impossible to make cargo-fuzz NOT use a sanitizer. This is usually worked around by using threadsan, as it doesn't do much for most programs, but I'm pretty sure that incurs some runtime cost.

I want to compile in release mode with no sanitizers to achieve maximum performance while looking for panics, as Rust eliminates most errors the sanitizers are made to detect.

**Comment by Manishearth** [comment]
This isn't possible, you must use a sanitizer to get the fuzzing instrumentation to work. This could perhaps be fixed by a PR to upstream rust.

**Comment by alex** [comment]
In C it's possible to get `-fsanitize-coverage=<trace-pc-guard, etc.>` without `-fsanitize=<address|memory|...>`

Is that not possible here?

**Comment by PaulGrandperrin** [comment]
It's true that right now, building without a sanitizer (by building your own version of cargo-fuzz) produces non-working targets but that shouldn't be the case.
While debugging an issue in rustc/llvm https://github.com/rust-lang/rust/issues/47953 , I came to build a toolchain with llvm6.0 and libfuzzer6.0.
And with this toolchain and a modified `cargo-fuzz` (without any sanitizers but more coverage trace points), the fuzzing works really well and is very fast!

**Comment by PaulGrandperrin** [comment]
for the record: https://github.com/rust-fuzz/libfuzzer-sys/issues/29

**Comment by kevincox** [comment]
Another use case for this is building with musl for a static library. This makes it really easy to ship a fuzzer to multiple machines. Right now none of the sanitizers are supported for musl. If I could build without sanitizers I believe I could build with musl.

**Comment by fitzgen** [comment]
This is supported now.
