### ISSUE TITLE
cargo-fuzz 0.5.0 release tag

### ISSUE THREAD

**Issue by kpcyrd** [rust-fuzz/cargo-fuzz#135]
It seems there was version 0.5.0 published on crates.io on Oct 3, 2017, but the github page still lists 0.4.3 as the most recent version. Could you tag the version you released as github release? This is relevant for [packaging](https://aur.archlinux.org/packages/cargo-fuzz/). Thanks! :)

**Comment by frewsxcv** [comment]
sorry for the delay! just added the tag, thanks for pointing this out 🙇

**Comment by kpcyrd** [comment]
Thanks, I've released 0.5.0 to the aur :)
