### ISSUE TITLE
ERROR: __sanitizer_reset_coverage is not defined. Exiting.

### ISSUE THREAD

**Issue by dwrensha** [rust-fuzz/cargo-fuzz#144]
Starting at some point in the past month or so, I am no longer able to run `cargo fuzz`. For example, with https://github.com/rust-fuzz/targets:

```
$ cargo fuzz --version
cargo-fuzz 0.5.2
$ rustc -vV
rustc 1.25.0-nightly (3ec5a99aa 2018-02-14)
binary: rustc
commit-hash: 3ec5a99aaa0084d97a9e845b34fdf03d1462c475
commit-date: 2018-02-14
host: x86_64-unknown-linux-gnu
release: 1.25.0-nightly
LLVM version: 6.0
$ ./run-fuzzer.sh httparse parse_request
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `/home/dwrensha/src/rust-fuzz-targets/target/x86_64-unknown-linux-gnu/debug/parse_request /home/dwrensha/src/rust-fuzz-targets/httparse/corpus /home/dwrensha/src/rust-fuzz-targets/httparse/seeds`
WARNING: Failed to find function "__sanitizer_get_total_unique_coverage".
WARNING: Failed to find function "__sanitizer_reset_coverage".
INFO: Seed: 3689636734
ERROR: __sanitizer_reset_coverage is not defined. Exiting.
Did you use -fsanitize-coverage=... to build your code?
```

**Comment by dwrensha** [comment]
My guess is that this is related to the recent LLVM update: https://github.com/rust-lang/rust/pull/47828

**Comment by frewsxcv** [comment]
Relevant [issue](https://github.com/rust-fuzz/libfuzzer-sys/issues/29) and [pull request](https://github.com/rust-fuzz/libfuzzer-sys/pull/30). I haven't had much time to review them though...

**Comment by frewsxcv** [comment]
https://github.com/rust-fuzz/libfuzzer-sys was just updated to support LLVM6 which should fix this issue. so just do a `cargo update` in the same dir as the cargo.toml that specifies libfuzzer-sys, probably `fuzz/`

**Comment by dwrensha** [comment]
Thanks!
