### ISSUE TITLE
Sanitizer internal functions not found

### ISSUE THREAD

**Issue by hsivonen** [rust-fuzz/cargo-fuzz#155]
Steps to reproduce (using rustc 1.27.0-nightly (acd3871ba 2018-05-10)):

1. `cargo install cargo-fuzz` (installed 0.5.2 for me)
2. `git clone https://github.com/hsivonen/encoding_rs`
3. `git clone https://github.com/hsivonen/safe_encoding_rs_mem`
4. `cd encoding_rs`
5. `cargo fuzz run fuzz_encodings`

Actual results:
```
WARNING: Failed to find function "__sanitizer_get_total_unique_coverage".
WARNING: Failed to find function "__sanitizer_reset_coverage".
INFO: Seed: 3831006704
ERROR: __sanitizer_reset_coverage is not defined. Exiting.
Did you use -fsanitize-coverage=... to build your code?
```

Expected results:
Expected fuzzing to start like with older versions.

**Comment by frewsxcv** [comment]
I followed your steps and I'm able to fuzz without any issues. I'm using `rustc 1.28.0-nightly (a3085756e 2018-05-19)`. Which platform are you on?

**Comment by hsivonen** [comment]
(Updated steps to reproduce to include `safe_encoding_rs_mem`.)

I see this with two computers that run x86_64 version of Ubuntu 16.04. I tried updating to the latest nightly.

I'll try Ubuntu 18.04 next.

**Comment by hsivonen** [comment]
Clean install of Ubuntu 18.04 plus `make`, `gcc` and `clang` from system repos works.

Could this be a conflict with the version of system clang libs? Do you want to keep this open to investigate further, or shall we just close this as "upgrade Ubuntu and move on"?

**Comment by frewsxcv** [comment]
I'm not sure to be honest, I also don't know what actionable thing there is here so I'd lean towards closing it.

**Comment by hsivonen** [comment]
OK. Let's close this. Thanks.
