### ISSUE TITLE
Cannot build fuzz targets in release mode: __sancov_guards has both ordered and unordered sections

### ISSUE THREAD

**Issue by ebarnard** [rust-fuzz/cargo-fuzz#161]
Running `cargo fuzz run -O TARGET` results in

```
/usr/bin/ld: __sancov_guards has both ordered [`__sancov_guards' in /home/me/rust-plist/fuzz/target/x86_64-unknown-linux-gnu/release/deps/binary_reader-f85fd5bec5488622.binary_reader.7pvxwz2b-cgu.1.rcgu.o] and unordered [`__sancov_guards' in /home/me/rust-plist/fuzz/target/x86_64-unknown-linux-gnu/release/deps/binary_reader-f85fd5bec5488622.binary_reader.7pvxwz2b-cgu.10.rcgu.o] sections

/usr/bin/ld: final link failed: Bad value
```

This can be worked around by forcing a single codegen unit i.e.

`RUSTFLAGS='-C codegen-units=1' cargo +nightly fuzz run -O TARGET`

so it is presumably related to thinlto.

Running:
Ubuntu 16.04 x86_64
rustc 1.31.0-nightly (b2d6ea98b 2018-10-07)
cargo-fuzz 0.5.2

**Comment by frewsxcv** [comment]
https://github.com/rust-lang/rust/issues/53945

**Comment by barrbrain** [comment]
Is this issue resolved by https://github.com/rust-fuzz/cargo-fuzz/pull/215?

**Comment by ebarnard** [comment]
I haven't had any issues with cargo-fuzz recently so I presume so.
