### ISSUE TITLE
Listing targets with color makes scripting difficult

### ISSUE THREAD

**Issue by marshallpierce** [rust-fuzz/cargo-fuzz#167]
I want to check that all fuzzers build in CI, and to do that I'd like to loop over the output of `cargo fuzz list`. However, that doesn't work on travis because of the color codes (apparently terminal detection isn't working):

```
error: no bin target named `(B[m[32mroundtrip_no_pad`
```

Are you open to removing color, or at least adding a `--no-color`? I don't think it's particularly useful to add a color when all the text is the same color anyway...

**Comment by frewsxcv** [comment]
> Are you open to removing color, or at least adding a `--no-color`? 

`--no-color` sounds good to me 👍

**Comment by marshallpierce** [comment]
OK, I'll take a stab at it when I have a moment or two.
