### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by steveklabnik** [rust-fuzz/cargo-fuzz#17]
First of all, the README says `--fuzz-target `, but it looks like it's `--target` now.

Secondly, with this script:

```rust
extern crate semver;

#![no_main]
extern crate fuzzer_sys;

use semver::Version;

#[export_name="LLVMFuzzerTestOneInput"]
pub extern fn go(data: &[u8]) {
    let _ = Version::parse("1.2.3");
}
```

I get this

```
error: an inner attribute is not permitted in this context
 --> fuzzers/fuzzer_script_1.rs:3:3
  |
3 | #![no_main]
  |   ^
  |
  = note: inner attributes and doc comments, like `#![no_std]` or `//! My crate`, annota
te the item enclosing them, and are usually found at the beginning of source files. Oute
r attributes and doc comments, like `#[test]` and
                                             `/// My function`, annotate the item follow
ing them.

error: main function not found
```

the no main stuff was generated by `--init`. I'm very confused.

**Comment by Manishearth** [comment]
`cargo install cargo-fuzz -f`, it changed from `--target` to `--fuzz-target`, you may need to reinstall. This crate is still under churn, I'll probably make a 1.0 when it settles down. Sorry!

>the no main stuff was generated by --init. I'm very confused.

`#![no_main]` has to be at the top of the module, due to how inner attributes work. I'll tweak the generated file to be clearer about this.

**Comment by steveklabnik** [comment]
> cargo install cargo-fuzz -f, it changed from --target to --fuzz-target, you may need to reinstall. 

I installed it just before creating this, maybe there's some other kind of bug? I'll try regardless.

> #![no_main] has to be at the top of the module, due to how inner attributes work. I'll tweak the generated file to be clearer about this.

Huh weird, I've never run into this because I usually put them up there anyway. Fun!

**Comment by Manishearth** [comment]
Oh! I didn't republish 😄

**Comment by Manishearth** [comment]
(it's republished now)
