### ISSUE TITLE
Support custom mutators

### ISSUE THREAD

**Issue by ruuda** [rust-fuzz/cargo-fuzz#170]
[Libfuzzer supports user-supplied mutators for structure-aware fuzzing.](https://github.com/google/fuzzer-test-suite/blob/530dae991ed41b4214a2a36844fecdf3f246cab9/tutorial/structure-aware-fuzzing.md) The user should provide a function

```cpp
extern "C" size_t LLVMFuzzerCustomMutator(
  uint8_t *Data,
  size_t Size,
  size_t MaxSize,
  unsigned int Seed
)
```

that mutates the data, and it can call `LLVMFuzzerMutate` to while doing so.

Would it be possible to support this in `cargo-fuzz`?

**Comment by Manishearth** [comment]
Not currently, we need weak symbol support in rustc.

What I might do is rejigger the libfuzzer API to let me pass this stuff in
by hand instead

**Comment by void0red** [comment]
Hi, can you provide some solutions?
I may need this feature very much. :)

**Comment by Manishearth** [comment]
You're welcome to experiment with this and provide a patch.

**Comment by fitzgen** [comment]
We already support custom mutators: https://docs.rs/libfuzzer-sys/latest/libfuzzer_sys/macro.fuzz_mutator.html
