### ISSUE TITLE
cargo fuzz run all

### ISSUE THREAD

**Issue by stepancheg** [rust-fuzz/cargo-fuzz#172]
I have a dozen of fuzz scripts.

It would be useful if `cargo fuzz run` could run them all. In the simplest case just for one second per target in a loop.

The use case is this: before release run the fuzzer for a night and check existing fuzz targets.

**Comment by Manishearth** [comment]
Fuzzing is supposed to be run indefinitely (and one second per fuzz isn't very useful at all). Different people would have different needs for this kind of thing (different timing requirements, etc). I recommend writing a script for this.

**Comment by stepancheg** [comment]
It should run indefinitely in a loop one second per fuzz target, preserving state.

**Comment by stepancheg** [comment]
Problem point is, if one have 20 fuzz target, it’s hard to automate running all of them for a night.

**Comment by Manishearth** [comment]
> It should run indefinitely in a loop one second per fuzz target, preserving state.

Fuzzers don't really support this kind of thing. You can build it by manually sending SIGSTP, I don't really think it belongs in cargo fuzz.
