### ISSUE TITLE
`cargo fuzz run` crashes on startup for some targets

### ISSUE THREAD

**Issue by Shnatsel** [rust-fuzz/cargo-fuzz#174]
When invoking `cargo fuzz run` it crashes on startup for me with message "deadly signal." The error message is distinct from the one on a crashing input. I'm compiling in default configuration, with ASAN, but still seeing this:
```
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
```

Full error message: https://pastebin.com/reeaqb6M

Fuzzing target:
https://gist.github.com/Shnatsel/80d31bd61ca7411f3e8f8a15ec63f141
Fuzzing targets for other crates work.

I've tried putting this into a binary crate without cargo-fuzz and it doesn't crash. Tried that both with and without address sanitizer.

Versions I've tried:
`rustc 1.35.0-nightly (3de010678 2019-04-11)`
`rustc 1.36.0-nightly (f49269398 2019-05-25)`

cargo-fuzz version 0.5.2, installed today

```
> uname -a
Linux that-desktop 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Manishearth** [comment]
This is a libFuzzer bug, I think. We don't actually deal with that here.

**Comment by nagisa** [comment]
Well, if updating libfuzzer would help, then it would probably belong here, but AFAIK there are changes in libfuzzer which make it incompatible with current rustc output, so we cannot update either way.
