### ISSUE TITLE
Add command to build all fuzz targets

### ISSUE THREAD

**Issue by pyfisch** [rust-fuzz/cargo-fuzz#175]
I want to make sure no fuzzer breaks without anyone noticing by building all fuzzers in Travis CI.

**Comment by yevgenypats** [comment]
Adding to this request is it possible to build only one fuzz target without running it using `cargo fuzz run`?

**Comment by fitzgen** [comment]
Yeah, I think this would ideally be like

```sh
# Build all fuzz targets
cargo fuzz build

# Build a specific target
cargo fuzz build my_target
```
