### ISSUE TITLE
--jobs should pass the argument to the fuzzer?

### ISSUE THREAD

**Issue by YaLTeR** [rust-fuzz/cargo-fuzz#181]
I am fuzzing my project and I noticed that when using parallel fuzzing with `--jobs` the corpus directory is never updated and the fuzzers never print anything but pulse. Not sure if it's an issue with my setup, but when I used `-- -jobs=n` instead of `--jobs` the corpus directory started to get updated fine, and fuzzers do print every type of log in their respective stdout files.

**Comment by YaLTeR** [comment]
Actually, it looks like it is indeed some setup issue or something... `-j` works fine on other fuzz targets.

**Comment by alex** [comment]
cargo-fuzz's `-j` implementation currently just spawns N copies of the binary. I think we should probably replace this implementation with `-fork': https://llvm.org/docs/LibFuzzer.html#fork-mode
