### ISSUE TITLE
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer

### ISSUE THREAD

**Issue by ia0** [rust-fuzz/cargo-fuzz#189]
When building with clang-7 instead of clang-6, I get the following error:
```
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
```
I'm not sure if it's an issue of cargo-fuzz or rustc or something else.

[example failure in travis](https://travis-ci.org/ia0/data-encoding/jobs/600462415#L667-L669)
[line causing travis failure](https://github.com/ia0/data-encoding/blob/9171cc1479b0761fb05f3cb31605b6853259c6b4/travis.sh#L67)

**Comment by nagisa** [comment]
Upgrade your cargo-fuzz.

**Comment by ia0** [comment]
Thanks @nagisa for your quick response. Indeed when installing cargo-fuzz even if it's already installed by changing this [line](https://github.com/ia0/data-encoding/blob/9171cc1479b0761fb05f3cb31605b6853259c6b4/travis.sh#L59), the compilation [succeeds](https://travis-ci.org/ia0/data-encoding/builds/600670333).

Thanks a lot!
