### ISSUE TITLE
Support running fuzz targets over specific input files

### ISSUE THREAD

**Issue by fitzgen** [rust-fuzz/cargo-fuzz#196]
libfuzzer allows one to run a fuzz target over specific existing inputs, *without* generating new inputs afterwards. You pass a list of files in on the command line. This is useful for running all the inputs in a corpus in CI for a pull request, for example.

However, if any of the CLI arguments is a directory, then libfuzzer goes into use-this-dir-as-a-corpus-and-generate-new-inputs mode. Because `cargo fuzz` automatically adds `fuzz/corpus/my-target` as a CLI argument, it always triggers this behavior.

We should have a way (new subcommand? new flag for `cargo fuzz run`?) to disable passing `fuzz/corpus/my-target`, and allow passing specific inputs on the command line without `--`.

```shell
cargo fuzz run-inputs my-target input1 input2 input3 ...
# or
cargo fuzz run my-target --no-auto-corpus input1 input2 input3 ...
```

**Comment by fitzgen** [comment]
Ah, so one workaround is to pass `-- -runs=0`, which will make libFuzzer exit after re-running each of the corpus's seeds, without generating any new inputs.

We may still want to add a `--only-existing-corpus` flag to do this, since it isn't obvious.

**Comment by kevincox** [comment]
I agree. I was trying to figure this out for a while with little success. Often once I found an issue I want to run that specific test case to fix the bug. I may also have downloaded a file for reproduction and we should have an easy way to reproduce it.

I think the `run` command would be nice. Because I want to work on a specific file, not whatever happens to be in the corpus. `cargo fuzz run my-target ~/Downloads/fuzzfail.bin` would be a nice workflow.

**Comment by fitzgen** [comment]
Agreed. I've quickly had my corpus grow larger than I want to wait to run in CI, so my earlier `-runs=0` workaround isn't scaling: I want to only run some sample of the corpus, not the whole thing.

I think we should overload `cargo fuzz run <target> <path...>` so that if all of `<path...>` are files, not directories, then we *don't* automatically pass the default corpus directory. Right now, if you do this, it will trigger an error (libfuzzer binaries want either directories or files). With the proposed change, it will run the fuzz target over those specific files, and not load the whole corpus and compute its pre-existing code coverage and all that.

@Manishearth does the above sound good to you? I can whip up a PR if so.

**Comment by Manishearth** [comment]
This works for me
