### ISSUE TITLE
Undefined reference to `rust_begin_unwind`

### ISSUE THREAD

**Issue by steveklabnik** [rust-fuzz/cargo-fuzz#20]
Ideas?

```text
  = note: /home/steve/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-cd0ca85e71f914ca.rlib(core-cd0ca85e71f914ca.0.o): In function `core::panicking::panic_fmt':
          /checkout/src/libcore/panicking.rs:69: undefined reference to `rust_begin_unwind'
          collect2: error: ld returned 1 exit status
```

I'm not doing anything special with regards to panics.

**Comment by Manishearth** [comment]
We run it with panic=abort, hmmm. Does your crate compile standalone with this?

**Comment by steveklabnik** [comment]
let me try, i dunno

**Comment by nagisa** [comment]
Can’t reproduce. Works just fine to me.

**Comment by neosilky** [comment]
Just tried with `semver` and it also works fine for me. Can this be closed?

**Comment by whitequark** [comment]
Closing as unable to reproduce--please comment if this is not so, @steveklabnik.

**Comment by steveklabnik** [comment]
I will probably not be able to for a long time, as I haven't set up any of this on Windows; closing seems good! Stuff has probably significantly changed since then.
