### ISSUE TITLE
Tagged 0.7.0 release dosn't build with --locked

### ISSUE THREAD

**Issue by kpcyrd** [rust-fuzz/cargo-fuzz#209]
Same issue as #168, it was fixed for the 0.6.0 release but broke again.

**Comment by fitzgen** [comment]
0.7.0 is the commit I did `cargo publish` with and the next commit after that is the one that updates the lockfile.

**Comment by kpcyrd** [comment]
Why? Cargo.toml and Cargo.lock are out of sync at 1325cf1428322a0b4e156fb35db95ddf1a106760. It's not possible to build the project at that commit without ending up with a dirty workspace.

**Comment by fitzgen** [comment]
Just because I did

* `cargo test`
* bump version
* `cargo publish`

instead of 

* bump version
* `cargo test`
* `cargo publish`

I'll make a point release with the updated lock file.
