### ISSUE TITLE
New fuzz targets should be marked `test = false` and `doc = false` in `Cargo.toml`

### ISSUE THREAD

**Issue by fitzgen** [rust-fuzz/cargo-fuzz#223]
The `test = false` is important because, if your fuzz targets are in the same workspace as the rest of your code, doing `cargo test --all` will accidentally just start the fuzzers running indefinitely because they have libfuzzer's main instead of the rustc test main.

The `doc = false` is just because these fuzz targets are internal and aren't exporting reusable bits elsewhere, so there's no point in documenting them.

Here is the code that needs these attributes added: https://github.com/rust-fuzz/cargo-fuzz/blob/master/src/templates.rs#L34-L36

And then this test should be modified to check that the `Cargo.toml` contains the expected metadata for the new fuzz target: https://github.com/rust-fuzz/cargo-fuzz/blob/master/tests/tests/main.rs#L101-L119

**Comment by dhaynespls** [comment]
Hey!

I started looking at this last night and adding the attributes to the template was simple, though I got stuck on how exactly the process for testing the `Cargo.toml` metadata would work. I was thinking the strategy is to like .. open it up, parse as toml and check if the attribute is there? Started going down a hole on that approach, though my Rust is still a little ... work in progress:

```rust
#[test]
fn add() {
    let project = project("add").with_fuzz().build();
    project
        .cargo_fuzz()
        .arg("add")
        .arg("new_fuzz_target")
        .assert()
        .success();
    assert!(project.fuzz_target_path("new_fuzz_target").is_file());
    // -----------------
    assert!(project.fuzz_cargo_toml().is_file());
    let my_toml = project.fuzz_cargo_toml();
    let mut file = fs::File::open(my_toml).unwrap();

    let mut data = Vec::new();
    file.read_to_end(&mut data).unwrap();
    let my_parsed_toml: toml::Value = toml::from_slice(&data).unwrap();
    let bins = my_parsed_toml
        .as_table()
        .and_then(|v| v.get("bin"))
        .and_then(toml::Value::as_array).unwrap();

    let mut bins = if let Some(bins) = bins {
        bins.iter()
            .map(|bin| {
                bin.as_table()
                    .and_then(|v| v.get("test"))
                    .and_then(toml::Value::as_str)
            })
            // .assert(|test| test == false) or something like that
    }
    // -----------------
    project
        .cargo_fuzz()
        .arg("run")
        .arg("new_fuzz_target")
        .arg("--")
        .arg("-runs=1")
        .assert()
        .success();
}
```

Was this along the lines of what you had in mind? If so I'll try taking a crack at refining it (well it doesn't work at present but I feel 90% of the way there) and if not, a pointer in the right direction would be much appreciated!

**Comment by fitzgen** [comment]
@dhaynespls, rather than parsing as toml, I think you can use `std::fs::read_to_string` and assert that it contains the expected snippet. While it isn't as precise of an assertion, this should be only a couple of lines of code, and a bit simpler to implement/maintain. Does that make sense?

**Comment by dhaynespls** [comment]
Much simpler, thanks!

Let me know if you'd like any changes.
