### ISSUE TITLE
Recommended reproduction command ignores arguments

### ISSUE THREAD

**Issue by HeroicKatora** [rust-fuzz/cargo-fuzz#228]
When running the fuzzer with specific sanitizer, time or memory settings and an issue is found then the output for reproduction is not complete. In particular the recommended command line for reproducing the issue misses any of these parameters as well as the used `cargo` version. Abbreviated example below.

```sh
$ cargo +nightly fuzz run some_fuzzer -sanitizer=memory
# ...
SUMMARY: MemorySanitizer: use-of-uninitialized-value (...)
Exiting
# ...
Reproduce with:

    cargo fuzz run some_fuzzer fuzz/artifacts/parser/crash-hash
```

When it should instead print:

```sh
Reproduce with:

    cargo +nightly fuzz run some_fuzzer -sanitizer=memory fuzz/artifacts/parser/crash-hash
```

**Comment by frewsxcv** [comment]
Thanks for reporting! Here's the code that needs to change:

https://github.com/rust-fuzz/cargo-fuzz/blob/2fb3bd85c0dd57ea7f3d5c29174c26a5550d0aa8/src/project.rs#L426-L436

We need to incorporate [the arguments](https://github.com/rust-fuzz/cargo-fuzz/blob/2fb3bd85c0dd57ea7f3d5c29174c26a5550d0aa8/src/options/run.rs#L30-L32) into the output.

**Comment by ian-fox** [comment]
> Thanks for reporting! Here's the code that needs to change:
> 
> https://github.com/rust-fuzz/cargo-fuzz/blob/2fb3bd85c0dd57ea7f3d5c29174c26a5550d0aa8/src/project.rs#L426-L436
> 
> We need to incorporate [the arguments](https://github.com/rust-fuzz/cargo-fuzz/blob/2fb3bd85c0dd57ea7f3d5c29174c26a5550d0aa8/src/options/run.rs#L30-L32) into the output.

I think the things we actually need here are from the `BuildOptions`. `args` holds things like `-runs` but not which sanitizers were used.

Unsure so far how to get the `+nightly` bit, I'll take a closer look at that tomorrow.

**Comment by nagisa** [comment]
`+nightly` comes from `rustup` wrapper, so I suspect its going to be out-of-scope for `cargo-fuzz`. But we can probably add a note to that effect? Like "note: if you're using rustup, you may need to specify `+nightly` to the cargo command".

**Comment by ian-fox** [comment]
That's probably the easiest way to do it. 

Alternatively it looks like when you call `rustup +toolchain <...>` it sets the `RUSTUP_TOOLCHAIN` variable based on what your override was. I don't see that documented though so maybe we don't want to depend on that.
