### ISSUE TITLE
Support for non-standard project directories

### ISSUE THREAD

**Issue by c410-f3r** [rust-fuzz/cargo-fuzz#238]
`fuzz` is currently the only possible directory name and it would be nice to have something like `cargo fuzz run --path some_fuzz_project_dir someTarget`

**Comment by hkratz** [comment]
That the directory containing the fuzzing code _has to be_ called "fuzz" (and cannot be renamed nor moved deeper in the directory structure) is undocumented is a limitation that is not documented anywhere. Is there a reason for it?
