### ISSUE TITLE
Merging raw coverage files fails with "Argument list too long" on macOS

### ISSUE THREAD

**Issue by jrmuizel** [rust-fuzz/cargo-fuzz#254]
I have a corpus of about 3483 different samples. Merging fails when running `llvm-profdata` because it lists each profraw file in the arguments. I believe `llvm-profdata` supports specifying a directory instead of individual file names. Doing that would probably solve this.

**Comment by fitzgen** [comment]
Ah that's no good!

I don't personally have the cycles to fix this right now, maybe @amaurremi does?

**Comment by silvergasp** [comment]
@jrmuizel Does #336 fix your issue?

You can check by running `cargo install --git https://github.com/silvergasp/cargo-fuzz.git cargo-fuzz`
