### ISSUE TITLE
Incompatible with nightly-2021-09-26: unknown pass name 'sancov'

### ISSUE THREAD

**Issue by dtolnay** [rust-fuzz/cargo-fuzz#276]
I noticed that serde_json's fuzz target does not build using the most recent nightly. It's been working for a long time so this is a recent breakage.

Repro:

```console
$ cargo fuzz init
$ cargo +nightly-2021-09-25 fuzz build  # works
$ cargo +nightly-2021-09-26 fuzz build

error: failed to run LLVM passes: unknown pass name 'sancov'

error: could not compile `once_cell` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bins"
```

The upstream commit range is https://github.com/rust-lang/rust/compare/73422130ee96c09e7214c876a3600ac1f32aa8c8...addb4da686a97da46159f0123cb6cdc2ce3d7fdb.

**Comment by dtolnay** [comment]
https://github.com/rust-lang/rust/pull/88243 looks like the most relevant change.

**Comment by nagisa** [comment]
There are two straightforward approaches to fixing this but either approach
will also prevent any operation with versions of rustc without newpm. It's
probably fine though?
