### ISSUE TITLE
cargo-fuzz --init does not work

### ISSUE THREAD

**Issue by nagisa** [rust-fuzz/cargo-fuzz#28]
```
$ cargo-fuzz --init
Invalid arguments.

Usage:
  cargo fuzz --init
```

Increasingly inclined to move from docopt to clap. I may get around to that eventually. Move to clap should also help with making a more flexible parser to pass various extra options to the executable and rustc.

**Comment by Manishearth** [comment]
I don't think clap solves this problem either.

**Comment by nagisa** [comment]
`clap` ignores 1st argument, so it does work just fine IIRC.
