### ISSUE TITLE
Importing issues in unpublished crates

### ISSUE THREAD

**Issue by HaramanJohal** [rust-fuzz/cargo-fuzz#281]
I am trying to fuzz some of my code but I am struggling with imports.

I have taken the following steps from the documentation:
1. `cargo install cargo-fuzz`
2. `cd my_project`
3. `cargo fuzz init`

but then when I try to import my modules into the file `fuzz_target_1.rs` I get various errors

If I try `extern crate my_project` (as in the docs) I get `can't find crate`
If I try `use my_project` I get `unresolved import` and `no external crate my_project`

Is there some other way I am supposed to access my code from the fuzz target?

`cargo fuzz init` has automatically included the following in `my_project/fuzz/Cargo.toml`:
```
[dependencies.my_project]
path = ".."
```
(I was under the impression that this means I can do something like `use my_project`)

If there is a more appropriate place for me to ask this question I am happy to direct it elsewhere
(I would be happy to update documentation myself if necessary once I understand how this works)

I'm sure this might be something really basic that I'm missing, thanks for your help!

**Comment by Manishearth** [comment]
This should work, the `..` should be enough to make it work; we really can't say more without seeing the code of your project. All of this is just standard cargo functionality, cargo-fuzz just generates the files.

**Comment by HaramanJohal** [comment]
Thanks for the response, I've tracked down the issue to this line in my project's `Cargo.toml`
```
crate-type = ["cdylib"]
```
I verified this in a minimal example which I got working with cargo-fuzz. I found that adding this line causes the undeclared crate errors.

I guess cargo-fuzz doesn't work for this type of library?

**Comment by Manishearth** [comment]
Yeah you should add rlib to that list

**Comment by HaramanJohal** [comment]
thanks for the help
