### ISSUE TITLE
Consider `cargo fuzz <fuzz target>` instead of `cargo fuzz --fuzz-target <fuzz target>`

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/cargo-fuzz#29]
Considering `cargo fuzz --fuzz-target <fuzz target>` is the main command here and going to be called the most, it seems unfortunate it's a pretty long CLI call. Maybe we should migrate to `cargo fuzz <fuzz target>`? Thoughts?

**Comment by nagisa** [comment]
I was thinking of doing that “implicitly” with a move to clap.

**Comment by Manishearth** [comment]
(I'm totally open to a move to clap or any other parser, I just picked docopt because cargo uses it. I'm also not attached to the current argument format. Go ahead and do whatever 😄 )

**Comment by nagisa** [comment]
This is fixed in #47, I think?

It is now `cargo fuzz run target`
