### ISSUE TITLE
libfuzzer development has stopped

### ISSUE THREAD

**Issue by kpcyrd** [rust-fuzz/cargo-fuzz#329]
It seems libfuzzer development has stopped:

![image](https://user-images.githubusercontent.com/7763184/208647004-6713cc98-b1c3-4752-8010-747537a2692d.png)

https://llvm.org/docs/LibFuzzer.html#status

Leaving this here since it's currently the default for cargo-fuzz. :)

**Comment by Manishearth** [comment]
Thanks, I think as long as it's being maintained we're fine here, it works well.
