### ISSUE TITLE
LibAFL support?

### ISSUE THREAD

**Issue by domenukk** [rust-fuzz/cargo-fuzz#330]
Now that libfuzzer has been [officially deprecated](https://llvm.org/docs/LibFuzzer.html#status) I was wondering if the maintainers of cargo-fuzz are interested to add [LibAFL](https://github.com/AFLplusplus/LibAFL) support to this crate directly.

LibAFL is not only maintained, but is written in Rust and has overall better performance [in benchmarks](https://fuzzbench.com/reports/2022-09-29/index.html).

So far, we maintain a fork of cargo-fuzz, called [cargo-libafl](https://github.com/AFLplusplus/cargo-libafl) and LibAFL can be a drop-in replacement for libfuzzer in general.

We can help out integrating this, but would need to know how to best add support, if this is something you are interested in.

**Comment by fitzgen** [comment]
I'm open to accepting pull requests that implement this. But I think we need design work before that happens.

One thing to figure out before hand is what the developer experience will be like and how this will/won't affect the CLI flags/commands. Ideally we won't require passing `--libafl` or `--libfuzzer` to every single command. Perhaps we can configure this in `Cargo.toml`?

**Comment by Manishearth** [comment]
FWIW Given that libFuzzer is not deprecated but in maintenance mode i'd prefer to make other fuzzers non-default options, fwiw.

Configuration in Cargo.toml makes sense, we can set the configuration on `cargo fuzz init` and `init` can have flags

**Comment by fitzgen** [comment]
Agreed.

**Comment by VTCAKAVSMoACE** [comment]
This is precisely why I opened https://github.com/rust-fuzz/libfuzzer/pull/103 :grin: (liblibafl...)

I'm finding what libafl lacks for compatibility and working on integration there: https://github.com/AFLplusplus/LibAFL/tree/libfuzzer
As of now, there are a couple of sancov items used that aren't currently supported by libafl, but most of the libfuzzer features are already supported. Should be a fairly straightforward replacement after that.

I'll bump here once we're compatible with `CUSTOM_LIBFUZZER_PATH`; after that, it should be fairly trivial to integrate via libfuzzer-sys.

**Comment by frewsxcv** [comment]
Considering changing the underlying fuzzer can be a breaking change (because of libfuzzer specific flags?), I think it's also worth having a discussion of how we introduce breaking changes in cargo-fuzz going forward.

**Comment by addisoncrump** [comment]
Actually, in this case, no -- the libfuzzer shim we wrote supports the same flags as libfuzzer, with some exceptions that won't affect the common use case. I already use my shim with cargo-fuzz for testing purposes.

**Comment by addisoncrump** [comment]
This is now supported by libfuzzer-sys via https://github.com/rust-fuzz/libfuzzer/pull/106.

**Comment by wcampbell0x2a** [comment]
@addisoncrump if I use `-j` for `cargo fuzz` do the fuzzers talk to each other like normal libAFL?

**Comment by wcampbell0x2a** [comment]
Also! How do I get stats on the amount of current coverage while it's running?

**Comment by Dr-Emann** [comment]
It looks like the upstream AFL++ [change](https://github.com/AFLplusplus/LibAFL/pull/981) has been merged, what else needs to happen for this?

**Comment by addisoncrump** [comment]
This is definitely completed, I just can't close the issue.

**Comment by domenukk** [comment]
`cargo fuzz init` doesn't have a flag yet to make this easy, does it?

**Comment by fitzgen** [comment]
Going to close this issue as the initial support has landed. Feel free to open new issues and make new PRs for further improvements.
