### ISSUE TITLE
Detect when code is reproducing a crash vs when it is fuzzing

### ISSUE THREAD

**Issue by mgeisler** [rust-fuzz/cargo-fuzz#343]
Hi all,

I have a lot of fun using `cargo fuzz` on my projects! It lowers the barrier enough that fuzzing becomes simple, so well done :+1: 

When I find a crash, I often need to debug it by adding extra `dbg!` or `eprintln!` calls to my code. Is there a way for me to leave this debug code in my fuzzer, but only activate it when I'm reproducing a crash?

I saw the `#[cfg(fuzzing)]` flag, but it is enabled equally in both cases (as it should be since reproducing the crash could rely on it). I looked at the command line arguments, but the only difference seems to be if the last argument is a directory or not. When I run `cargo fuzz run backends_rust_generate` I see:
```rust
[fuzz_targets/backends_rust_generate.rs:7] std::env::args().collect::<Vec<_>>() = [
    "fuzz/target/x86_64-unknown-linux-gnu/release/backends_rust_generate",
    "-artifact_prefix=/home/mgeisler/src/pdl/fuzz/artifacts/backends_rust_generate/",
    "/home/mgeisler/src/pdl/fuzz/corpus/backends_rust_generate",
]

```

vs when reproducing a crash with `cargo fuzz run backends_rust_generate fuzz/artifacts/backends_rust_generate/crash-a3d9424297fe7b773102352b48b7bdd6b0457430`:

```rust
[fuzz_targets/backends_rust_generate.rs:7] std::env::args().collect::<Vec<_>>() = [
    "fuzz/target/x86_64-unknown-linux-gnu/release/backends_rust_generate",
    "-artifact_prefix=/home/mgeisler/src/pdl/fuzz/artifacts/backends_rust_generate/",
    "fuzz/artifacts/backends_rust_generate/crash-c9b96795bcb23158a324f38824d56e24f04b6426",
]
```

Ideally, there would be another `cfg` value I can use to completely compile away the debug prints when fuzzing. Does that exist?

**Comment by Manishearth** [comment]
I would be in support of a `cfg(fuzz_repro)` or something.

**Comment by mgeisler** [comment]
> I would be in support of a `cfg(fuzz_repro)` or something.

Cool, I opened #344 to implement this.

**Comment by addisoncrump** [comment]
I highly recommend using tmin in these cases if you are not already... many times, I will learn more from the input than I will from the debugging :sweat_smile:

**Comment by mgeisler** [comment]
@addisoncrump, hehe, yeah I do use that and it's amazing to see it boil down my input :smile: 

I've been [fuzzing pulldown-cmark recently](https://github.com/raphlinus/pulldown-cmark/pull/663) and there I found it super useful to be able to see the Markdown AST of inputs. I was able to order things so that I could print out the debug output only when I detect a problem, but it could have been nice to just sprinkle it all over the fuzzer instead.
