### ISSUE TITLE
Add ability to pass extra options to libFuzzer

### ISSUE THREAD

**Issue by oyvindln** [rust-fuzz/cargo-fuzz#39]
Being able to adjust some of the libFuzzer options (e.g max_len) would be useful, currently this seems to be only possible by editing the source of cargo-fuzz or using libFuzzer directly.

A simple solution would be to provide some pass-through argument to cargo fuzz that will passed to libFuzzer. (Similar to what rustc has with llvm options.)

**Comment by nagisa** [comment]
Duplicate of https://github.com/rust-fuzz/cargo-fuzz/issues/3
