### ISSUE TITLE
Consider adding a full tutorial / book via mdbook

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/cargo-fuzz#41]
Similar to what afl.rs has:

https://rust-fuzz.github.io/afl.rs/

https://github.com/rust-fuzz/afl.rs/tree/master/docs/src

I'd be willing to write it if others think it'd be helpful.

It also might make sense to have a new repository: rust-fuzz/book

**Comment by Manishearth** [comment]
I think it would be helpful.

Merging the books works for me too.

**Comment by sanmai-NL** [comment]
I could find https://rust-fuzz.github.io/book/cargo-fuzz/targets.html
Let's append it to the project description on GitHub and to the `README`.
Then, issue resolved, or ...?

**Comment by sanmai-NL** [comment]
There's https://rust-fuzz.github.io/book/cargo-fuzz.html and that seems to cover `cargo-fuzz` already.
Let's append it to the project description on GitHub and to the `README`.
Then, issue resolved, or ...?
