### ISSUE TITLE
Entity not found

### ISSUE THREAD

**Issue by ner0x652** [rust-fuzz/cargo-fuzz#44]
Running `cargo fuzz --fuzz-target fuzzer_script_1` results in a `Error: Entity not found`.

Discussed with @nagisa about this issue on IRC, the cause is
> "since we started passing in the `--target=xxx` flag, it puts the executable in `fuzz/target/<TARGET>/debug` where cargo-fuzz looks for it in `fuzz/target/debug`"

**Comment by nagisa** [comment]
After https://github.com/rust-fuzz/cargo-fuzz/pull/51 this should be fixed.
