### ISSUE TITLE
Should cargo-fuzz generate dummy fuzzer with macro util?

### ISSUE THREAD

**Issue by frewsxcv** [rust-fuzz/cargo-fuzz#46]
https://github.com/rust-fuzz/cargo-fuzz/blob/99c3647b1f0a7c4902108d64ff706d2c29f695b9/src/main.rs#L155-L163

https://github.com/rust-fuzz/libfuzzer-sys/blob/d899978f3f4d594d1495a277ac184271e180b4be/src/lib.rs#L18-L32

**Comment by Manishearth** [comment]
yes.
