### ISSUE TITLE
add check artifact command

### ISSUE THREAD

**Issue by pyfisch** [rust-fuzz/cargo-fuzz#60]
If the program panics an artifact is written. I then try to fix the bug causing the panic. Now I want to check if I really fixed the bug. A command like 
`cargo fuzz check my_fuzzer crash-2c66bb9f0dabeaf158f68a7eea3b5033080173c3` would be useful that invokes `go(data)` with this artifact again.

**Comment by nagisa** [comment]
This is easy to achieve. The libfuzzer binaries, if passed a file instead of directory as an argument, will run the function with exactly the data in the file.

We need to have per-target corpus and artefact directories implemented first, though.

**Comment by emk** [comment]
Another good option is to create a test case that loads all the artifacts you've ever generated, and checks all of them. Here's [an example from one of my crates](https://github.com/emk/subtitles-rs/blob/cf054bf5c2a017e99afc921c6725f044a2f54924/vobsub/tests/parse_corpus.rs#L30-L45).

I agree that having some automatic support for this would be handy, though.
