### ISSUE TITLE
-fsanitize-coverage=trace-cmp

### ISSUE THREAD

**Issue by emk** [rust-fuzz/cargo-fuzz#64]
According to the [libfuzzer documentation](http://llvm.org/docs/LibFuzzer.html#id32), there's a `-fsanitize-coverage=trace-cmp` flag that looks interesting:

> ### Tracing CMP instructions
>
> With an additional compiler flag -fsanitize-coverage=trace-cmp (see SanitizerCoverageTraceDataFlow) libFuzzer will intercept CMP instructions and guide mutations based on the arguments of intercepted CMP instructions. This may slow down the fuzzing but is very likely to improve the results.
>
> ### Value Profile
>
> EXPERIMENTAL. With -fsanitize-coverage=trace-cmp and extra run-time flag -use_value_profile=1 the fuzzer will collect value profiles for the parameters of compare instructions and treat some new values as new coverage.
>
> ...
>
> This feature has a potential to discover many interesting inputs, but there are two downsides. First, the extra instrumentation may bring up to 2x additional slowdown. Second, the corpus may grow by several times.

Is there any easy way to turn this on using `cargo fuzz`?

**Comment by nagisa** [comment]
Set `RUSTFLAGS` to `-Cllvm-args=-sanitizer-coverage-experimental-trace-compares`.

Will not be exposed from cargo fuzz in a more simple way due to it being… experimental, unstable and finicky in general.

**Comment by whitequark** [comment]
Closing per above.
