### ISSUE TITLE
How to disable memory leaks detection?

### ISSUE THREAD

**Issue by RazrFalcon** [rust-fuzz/cargo-fuzz#73]
I'm getting:
```
SUMMARY: AddressSanitizer: 433 byte(s) leaked in 3 allocation(s).
INFO: a leak has been found in the initial corpus.
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

I don't know is it are real leaks because it triggered by `Rc::new()`.

PS: maybe this issue should be treated as "How to pass custom flags to libFuzzer", which is not done yet (AFAIK).

**Comment by nagisa** [comment]
Cargo fuzz run target -- flags

**Comment by RazrFalcon** [comment]
Thanks. It works. Maybe it should be added to readme? Even through it's a default cargo behavior.

**Comment by frewsxcv** [comment]
You should be able to specify `ASAN_OPTIONS="detect_leaks=0"` now after the changes in https://github.com/rust-fuzz/cargo-fuzz/pull/84

**Comment by frewsxcv** [comment]
....or yeah, just pass it as flags to `cargo fuzz run`
