### ISSUE TITLE
workspace member `Cargo.toml` is not hierarchically below the workspace root  `fuzz/Cargo.toml`

### ISSUE THREAD

**Issue by budziq** [rust-fuzz/cargo-fuzz#80]
Hi,

I wanted to checkout cargo fuzz but the `cargo fuzz run fuzzer_script_1` fails on freshly created cargo workspace
```
cargo init test_fuzz
cd test_fuzz 
cargo fuzz init
```

Fails with:

`error: workspace member '/path/to/test_fuzz/Cargo.toml' is not hierarchically below the workspace root '/path/to/test_fuzz/fuzz/Cargo.toml'`

I am testing on the latest  stable:
rustc 1.15.1 (021bd294c 2017-02-08)
cargo 0.16.0-nightly (6e0c18c 2017-01-27)

To duble check with some other example from github
https://github.com/Manishearth/unicode-segmentation.git (checked out the `fuzz` branch and corrected the `[package.metadata]` in fuzz/cargo.toml) and unfortunately the result was identical.

`error: workspace member '/path/to/unicode-segmentation/Cargo.toml' is not hierarchically below the workspace root '/path/to/unicode-segmentation/fuzz/Cargo.toml'`

Am I doing something wrong or are the instructions outdated?

**Comment by ner0x652** [comment]
Hi,

It seems that you ran into this issue https://github.com/rust-lang/cargo/issues/3192

You can add to `test_fuzz`'s `Cargo.toml` the following:
```
[workspace]
members = ["."]
```
I don't guarantee that it'll work. I have the same issue in a PR https://github.com/rust-fuzz/cargo-fuzz/pull/79

Hope this helps! :crossed_fingers:

**Comment by budziq** [comment]
Hi,

Thanks for help @ner0x652 but unfortunately no dice. I get the same error as you in your PR #79
```
error: multiple workspace roots found in the same workspace:
  /path/to/test_fuzz/fuzz
  /path/to/test_fuzz
```

**Comment by budziq** [comment]
Well it seams that running on nightly compiler `cargo +nightly fuzz run fuzzer_script_1` does the trick right off the bat on fresh setup without any [workspace] clause moddifications.

I guess that rust stable is currently unsupported (more digging eventually gave me rustc error about sanitize option not being supported anyway)

**Comment by ner0x652** [comment]
👍 
I guess there is some code addressing this issue on nightly, probably implementing the idea of @alexcrichton(mentioned in the Cargo issue tracker, link to that is in my first comment).

**Comment by nagisa** [comment]
Nightly requirement is explicitly noted in the readme.

On Mar 8, 2017 4:12 PM, "Michał" <notifications@github.com> wrote:

Well it seams that running on nightly compiler cargo +nightly fuzz run
fuzzer_script_1 does the trick right off the bat on fresh setup without any
[workspace] clause moddifications.

I guess that rust stable is currently unsupported (more digging eventually
gave me rustc error about sanitize option not being supported anyway)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rust-fuzz/cargo-fuzz/issues/80#issuecomment-285050566>,
or mute the thread

**Comment by budziq** [comment]
@nagisa After grepping readme for "nightly" I see that it in fact is stated as a requirement.
I would suggest to update the readme a little as it is not fool proof (fool being the operative word here :disappointed:) 
I would either mark the "nightly" with bold or add `cargo +nightly fuzz run fuzzer_script_1` to the example

**Comment by nagisa** [comment]
The +nightly is only valid with rustup.
