### ISSUE TITLE
Document the meaning of output

### ISSUE THREAD

**Issue by Kixunil** [rust-fuzz/cargo-fuzz#83]
I tried this but I don't understand what the output means. It'd be helpful if it was documented.

**Comment by Bobo1239** [comment]
The output is documented [here](http://llvm.org/docs/LibFuzzer.html#output). Not sure if writing new documentation is useful but we should at least link to it somewhere.

**Comment by Kixunil** [comment]
Ah, thank you! Yes, link would be good.
