### ISSUE TITLE
RUSTFLAGS are ignored

### ISSUE THREAD

**Issue by vks** [rust-fuzz/cargo-fuzz#9]
It seems like `RUSTFLAGS` are ignored when compiling the fuzzer script. This makes it impossible to fuzz crates that rely on e.g. AVX2.

**Comment by Manishearth** [comment]
We reset RUSTFLAGS.

**Comment by vks** [comment]
Well, how can I fuzz crates with user-defined `RUSTFLAGS` then? Couldn't `cargo fuzz` respect the user-defined `RUSTFLAGS`?

**Comment by Manishearth** [comment]
Yes, it could, we just haven't added that functionality 😄 

If you want you can easily add it by appending the contents of the var to https://github.com/rust-fuzz/cargo-fuzz/blob/master/src/main.rs#L192
